name = "GradientBoosting"
uuid = "a108434f-6647-5a5d-ae94-d05b8175566d"
keywords = ["Gradient Boosting"]
license = "MIT"
desc = "The Julia implementation of Gradient Boosting."
version = "1.0.0"

[deps]
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"